Automated Dev Commit : 2025-12-24 02:03:41 PM

diff --git a/config/.local/bin/upload b/config/.local/bin/upload
--- a/config/.local/bin/upload
+++ b/config/.local/bin/upload
@@ -2,6 +2,8 @@
 ezauth="$EZAUTH"
 ezuploadurlt="https://api.e-z.host/paste/file"
 ezuploadurlf="https://api.e-z.host/files"
+monarchauth="secret=$MONARCHKEY"
+monarchuploadurl="https://api.monarchupload.cc/v3/upload"
 
 
 if [[ $# -ne 1 ]]; then
@@ -13,43 +15,64 @@ FILENAME="$(realpath "$1")"
 BASENAME="$(basename "$FILENAME")"
 TEMP="/tmp/${BASENAME%.txt}.txt"
 
-echo "Uploading: $FILENAME"
+# EZ
+# echo "Uploading: $FILENAME"
+#
+# # Check if file exists and is readable
+# if [[ ! -f "$FILENAME" || ! -r "$FILENAME" ]]; then
+#     echo "Error: File '$FILENAME' does not exist or is not readable."
+#     exit 1
+# fi
+#
+# # Determine file type
+# FILE_TYPE=$(file --mime-type -b "$FILENAME")
+#
+# # Upload logic
+# case "$FILE_TYPE" in
+#     text/*)
+#         cp "$FILENAME" "$TEMP"
+#         json_data=$(curl -X POST -F "file=@$TEMP" -H "key:$ezauth" -v "$ezuploadurlt" 2>/dev/null)
+#         file_url=$(echo "$json_data" | jq -r '.pasteUrl')
+#         rm "$TEMP"
+#         ;;
+#     image/* | video/* | audio/* | application/zip | application/x-zip-compressed )
+#         json_data=$(curl -X POST -F "file=@$FILENAME" -H "key:$ezauth" -v "$ezuploadurlf" 2>/dev/null)
+#         file_url=$(echo "$json_data" | jq -r '.imageUrl')
+#         ;;
+#     *)
+#         echo "Error: Unsupported file type ($FILE_TYPE)."
+#         # notify-send "File Not Valid" -a "Trix Uploader"
+#         exit 1
+#         ;;
+# esac
+#
+# # Copy URL to clipboard and notify
+# if [[ -n "$file_url" && "$file_url" != "null" ]]; then
+#     echo "$file_url"
+#     echo -n "$file_url" | wl-copy
+#     notify-send "File URL copied to clipboard" "$file_url" -a "Trix Uploader"
+# else
+#     echo "Upload failed."
+#     notify-send "Upload Failed" -a "Trix Uploader"
+# fi
+#
 
-# Check if file exists and is readable
 if [[ ! -f "$FILENAME" || ! -r "$FILENAME" ]]; then
     echo "Error: File '$FILENAME' does not exist or is not readable."
     exit 1
 fi
 
-# Determine file type
-FILE_TYPE=$(file --mime-type -b "$FILENAME")
 
-# Upload logic
-case "$FILE_TYPE" in
-    text/*)
-        cp "$FILENAME" "$TEMP"
-        json_data=$(curl -X POST -F "file=@$TEMP" -H "key:$ezauth" -v "$ezuploadurlt" 2>/dev/null)
-        file_url=$(echo "$json_data" | jq -r '.pasteUrl')
-        rm "$TEMP"
-        ;;
-    image/* | video/* | audio/* | application/zip | application/x-zip-compressed )
-        json_data=$(curl -X POST -F "file=@$FILENAME" -H "key:$ezauth" -v "$ezuploadurlf" 2>/dev/null)
-        file_url=$(echo "$json_data" | jq -r '.imageUrl')
-        ;;
-    *)
-        echo "Error: Unsupported file type ($FILE_TYPE)."
-        # notify-send "File Not Valid" -a "Trix Uploader"
-        exit 1
-        ;;
-esac
-
-# Copy URL to clipboard and notify
-if [[ -n "$file_url" && "$file_url" != "null" ]]; then
-    echo "$file_url"
-    echo -n "$file_url" | wl-copy
-    notify-send "File URL copied to clipboard" "$file_url" -a "Trix Uploader"
+json_data=$(curl -s -F $monarchauth -F "file=@$FILENAME" $monarchuploadurl)
+file_url=$(echo "$json_data" | jq -r '.data.url')
+message=$(echo "$json_data" | jq -r '.message')
+status=$(echo "$json_data" | jq -r '.status')
+if [ "$status" = "success" ]; then
+    echo $message
+    wl-copy "$file_url"
 else
-    echo "Upload failed."
-    notify-send "Upload Failed" -a "Trix Uploader"
+    # notify-send -a "Gpu Screen Recorder" -i "screenrecorder" -u critical -t 10000 -h string:x-canonical-private-synchronous:shot-notify "$message"
+    echo $message
+    exit 1
 fi
-
+exit 0
